### ISSUE TITLE
Split item cost example

### ISSUE THREAD

**Issue by pv-aiuta-com** [aws-samples/aws-usage-queries#8]
Would be great to have here some examples for aggregating cost by split items (e.g. EKS deployment)
https://docs.aws.amazon.com/cur/latest/userguide/table-dictionary-cur2-split-line-item.html
For some reason I got 3x costs there while grouping by them, while the same approach works well for calculating costs like S3 and VPC.

**Comment by steffeng** [comment]
Hi @pv-aiuta-com, can you confirm which query you are using to group the data?

**Comment by pv-aiuta-com** [comment]
Hey @steffeng . Thank you for your response. I export CUR 2.0 reports as parquet files. Then I daily load these parquet dumps to a BigQuery table. 
Actually the problem is not with the split items, but with finding the total cost for some aggregations.

If I just aggregate the entries to find cost per date, aws account and AWS product like this
```
  SELECT
    EXTRACT(DATE FROM line_item_usage_start_date)AS date,
    line_item_usage_account_name AS account,
    line_item_product_code AS service, 
    SUM(line_item_unblended_cost) AS cost,
  FROM
    `<mytable>`
  WHERE
    line_item_line_item_type = "Usage"  
  GROUP BY 
      EXTRACT(DATE FROM line_item_usage_start_date)),
      line_item_usage_account_name,
      line_item_product_code
```
I'm getting absolute number that is much higher than in AWS Console Cost Explorer.

Then I try to remove potential duplicate entries like this:
```
SELECT 
  date,
  account,
  service, 
  ROUND(SUM(cost), 2) AS cost 
FROM 
(
  SELECT
    ANY_VALUE(EXTRACT(DATE FROM line_item_usage_start_date)) AS date,
    ANY_VALUE(line_item_usage_account_name) AS account,
    ANY_VALUE(line_item_product_code) AS product, 
    MAX(line_item_unblended_cost) AS cost,
  FROM
    `<mytable>`
  WHERE
    line_item_line_item_type = "Usage" 
  GROUP BY identity_line_item_id
)
GROUP BY 
  date, account, product
ORDER BY 
  date, account, product, cost DESC;
```
The cost is much closer but still higher than in AWS Console Cost Explorer


And to aggregate split items cost I do:
```
SELECT 
  line_item_usage_start_date AS date,
  line_item_usage_account_name AS account,
  deployment_name, 
  ROUND(SUM(split_line_item_split_cost), 2) AS cost
FROM 
(
  SELECT
  ANY_VALUE(line_item_usage_account_name) AS line_item_usage_account_name,
  ANY_VALUE(REGEXP_EXTRACT(line_item_resource_id, <some regexp>) AS deployment_name,  
  ANY_VALUE(EXTRACT(DATE FROM line_item_usage_start_date)) AS line_item_usage_start_date,
  MAX(split_line_item_split_cost) AS split_line_item_split_cost,

  FROM
    `<mytable>`
  WHERE 
    line_item_line_item_type = "Usage" 
  GROUP BY identity_line_item_id
)
GROUP BY 
  line_item_usage_start_date,
  line_item_usage_account_name,
  deployment_name
ORDER BY 
  date,
  account,
  cost DESC;
```
And the cost is also higher than in AWS Console Cost Explorer

**Comment by steffeng** [comment]
I'm sorry, I don't have a curated query for CUR 2, split cost allocation, or instructions how to use it with BigQuery.

Possible pointers of what you can do next:

- turn to [CID and their SCAD sample dashboards](https://catalog.workshops.aws/awscid/en-US/dashboards/additional/scad-containers-cost-allocation). Which are more comprehensive with their curated queries. Check how this aligns Cost Explorer in your case.
- as [they don't support CUR 2 either, yet](https://github.com/aws-samples/aws-cudos-framework-deployment/issues/750), try the legacy CUR.

**Comment by pv-aiuta-com** [comment]
Thank you. WIll check these

**Comment by steffeng** [comment]
Thanks, Peter!
